// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApp_EfCore1.DBFirstModels;

public partial class City
{
    public int Id { get; set; }

    public string LocationName { get; set; }

    public virtual ICollection<Department> Departments { get; set; } = new List<Department>();
}