// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApp_EfCore1.DBFirstModels;

public partial class Customer
{
    public int Id { get; set; }

    public string CustomerName { get; set; }

    public string CustomerEmail { get; set; }

    public string Address { get; set; }

    public string CreatedBy { get; set; }

    public DateTime CreatedOn { get; set; }

    public string LastModifiedBy { get; set; }

    public DateTime? LastModifiedOn { get; set; }

    public string City { get; set; }
}