// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApp_EfCore1.DBFirstModels;

public partial class Employee
{
    public int Id { get; set; }

    public string EmployeeName { get; set; }

    public string Gender { get; set; }

    public int Age { get; set; }

    public string Address { get; set; }

    public string CreatedBy { get; set; }

    public DateTime CreatedOn { get; set; }

    public string LastModifiedBy { get; set; }

    public DateTime? LastModifiedOn { get; set; }

    public int DepartmentId { get; set; }

    public virtual Department Department { get; set; }
}