// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebApp_EfCore1.DBFirstModels
{
    public partial class GetEmpById_with_OutputParamResult
    {
        public int Id { get; set; }
        [StringLength(200)]
        public string EmployeeName { get; set; }
        [StringLength(2)]
        public string Gender { get; set; }
        public int Age { get; set; }
        [StringLength(2147483647)]
        public string Address { get; set; }
        [StringLength(100)]
        public string DepartmentName { get; set; }
        [StringLength(50)]
        public string LocationName { get; set; }
    }
}
