// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;
using WebApp_EfCore1.DBFirstModels;

namespace WebApp_EfCore1.DBFirstModels
{
    public partial interface IFusionStackDbFirstContextProcedures
    {
        Task<List<GetEmpByIdResult>> GetEmpByIdAsync(int? id, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetEmpById_with_OutputParamResult>> GetEmpById_with_OutputParamAsync(int? id, OutputParameter<int?> totalCount, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
